### ISSUE TITLE
Fantastic Heaven doesn't work since server migration

### ISSUE THREAD

**Issue by worra95** [Prowlarr/Indexers#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to add Fantastic Heaven as Indexer an error is shown when clicking on save. The indexer worked until last weekend when Fantastic Heaven did a server migration. URL stayed the same, but now a PIN is required instead of the captcha (like https://new-retro.eu/)

### Expected Behavior

When I add Fantastic Heaven as Indexer I can click save and the Indexer is configured successfully.

### Steps To Reproduce

Add Indexer -> Choose Fantastic Heaven
Add credentials and solve captcha (capcha not possible anymore)
click save

### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- Prowlarr: 0.4.4.1947
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox/Chrome
```

### What branch are you running?

Develop

### Trace Logs?

Unable to connect to indexer: Login failed: No form found on https://fantastic-heaven.eu/login.php using form selector form[action="/login.php"]

NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannConfigException: Login failed: No form found on https://fantastic-heaven.eu/login.php using form selector form[action="/login.php"]
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 250
   at NzbDrone.Core.Indexers.Cardigann.Cardigann.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\Cardigann.cs:line 166
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 382
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 314
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 511

An unhandled exception has occurred while executing the request.: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
 
 FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 209
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

[AB#3709](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3709)

[AB#3710](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3710)

**Comment by ilike2burnthing** [comment]
Should be fixed in https://github.com/Prowlarr/Indexers/commit/7fe0e62ef96bcdb0b85b51ca1329db8814ef266a

**Comment by worra95** [comment]
@ilike2burnthing should this already be fixed in prowlarr version 0.4.5.1960?
Just asking because Fantastic Heaven is now available with PIN,... but it is still not working. Maybe the reason is the missing Base URL?
If this should already be fixed, I can provide the corresponding logs.
Thanks

**Comment by ilike2burnthing** [comment]
Yes.

Missing Base URL?

**Comment by worra95** [comment]
@ilike2burnthing the Base URL-dropdown is empty. Don't know if this affects the functionality. 
![image](https://user-images.githubusercontent.com/47828905/191059196-52937c81-1570-41f1-9712-a9ff53736ca0.png)
But for me it is still not working: 

[prowlarr_logs.txt](https://github.com/Prowlarr/Indexers/files/9600534/prowlarr_logs.txt)

**Comment by Qstick** [comment]
Shouldn't be empty, but that shouldn't cause issues. In Prowlarr empty BaseUrl means it uses the default.

Your defs might be out of date?

**Comment by worra95** [comment]
What exactly is ment by defs? The prowlarr version?

**Comment by ilike2burnthing** [comment]
Definitions, the files for the indexers. Go to Prowlarr > System > Tasks and check the Last Execution of Indexer Definition Update, or trigger one yourself.

However, if you're seeing the PIN field, then it's up to date, and it's working for me on Jackett and Prowlarr.

I suggest deleting the indexer, restarting Prowlarr, sign out of fantastic-heaven.eu, sign back in, and make sure you can access the browse page. If you have no issues on the tracker itself, then add the indexer in Prowlarr again, only entering your username, password, and PIN, don't select the filters or sort/order. If that works, then you can try reconfiguring the indexer as you like.
